import board
from micropython import const

LIS3DH_I2C_ADDR = const(0x19)
SHT30_I2C_ADDR = const(0x44)
NFC_I2C_ADDR = const(0x55)

I2C_SDA = board.GP8
I2C_SCL = board.GP9

AMBIENT_LIGHT_ANALOG = board.GP26_A0

NFC_FIELD_DETECT = board.GP6

DISPLAY_SPI_CS = board.GP17
DISPLAY_SPI_SCK = board.GP18
DISPLAY_SPI_MISO = board.GP16
DISPLAY_SPI_MOSI = board.GP19
DISPLAY_BACKLIGHT = board.GP20
DISPLAY_DC = board.GP21

EXPRESSLINK_TX = board.GP0
EXPRESSLINK_RX = board.GP1
EXPRESSLINK_DEBUG_TX = board.GP4
EXPRESSLINK_DEBUG_RX = board.GP5
EXPRESSLINK_EVENT = board.GP10
EXPRESSLINK_WAKE = board.GP11
EXPRESSLINK_RESET = board.GP12

NEOPIXEL_DATA = board.GP7
NEOPIXEL_CHAIN_LENGTH = 5

BUTTON1 = board.GP13
BUTTON2 = board.GP14
BUTTON3 = board.GP15
